accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup_user

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup_user, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("home")),
        name="home_redirect",
    ),
]

receipts/urls.py
from django.urls import path
from .views import (
    ReceiptListView,
    ExpenseCategoryListView,
    AccountListView,
    ReceiptCreateView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)


urlpatterns = [
    path(
        "",
        ReceiptListView.as_view(),
        name="home",
    ),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path(
        "accounts/",
        AccountListView.as_view(),
        name="list_accounts",
    ),
    path(
        "create/",
        ReceiptCreateView.as_view(),
        name="create_receipt",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_account",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.name)


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.name)


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def signup_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

receipts/views.py
# from django.shortcuts import render
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Receipt, ExpenseCategory, Account


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        return super().form_valid(form)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/create.html"
    fields = ["name"]
    success_url = reverse_lazy("list_categories")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]
    success_url = reverse_lazy("list_accounts")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

accounts/templates/navbar.html
<header>
  <nav>
    <ul>
      {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        <p>
          <li>
            <a href="{% url 'home' %}">See all Receipt</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">See all Expense Categories</a>
          </li>
          <li>
            <a href="{% url 'list_accounts' %}">See all Acccounts</a>
          </li>
        </p>
        <p>
          <li>
            <a href="{% url 'create_receipt' %}">Add Receipt</a>
          </li>
          <li>
            <a href="{% url 'create_category' %}">Add Expense Category</a>
          </li>
          <li>
            <a href="{% url 'create_account' %}">Add Acccount</a>
          </li>
        </p>
      {% else %}
        <li>
          <a href="{% url 'signup' %}">Sign Up</a>
        </li>
        <li>
          <a href="{% url 'login' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </nav>
</header>

receipts/templates/accounts/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
  </head>
  {% include "navbar.html" %}

  <body>
    <main>
      <div>
        <h1>Create Account</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button>Create</button>
        </form>
      </div>
    </main>
  </body>
</html>

receipts/templates/accounts/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Accounts</title>
  </head>
  {% include "navbar.html" %}

  <body>
    <main>
      <h1>My Accounts</h1>
      <table>
        <thead>
          <th>Name</th>
          <th>Number</th>
          <th>Number of receipts</th>
        </thead>
        <tbody>
          {% for account in account_list %}
            <tr>
              <td>{{ account.name }}</td>
              <td>{{ account.number }}</td>
              <td>{{ account.receipts.all|length }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>

receipts/templates/categories/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Category</title>
  </head>
  {% include "navbar.html" %}

  <body>
    <main>
      <div>
        <h1>Create Category</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button>Create</button>
        </form>
      </div>
    </main>
  </body>
</html>

receipts/templates/categories/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Categories</title>
  </head>
  {% include "navbar.html" %}

  <body>
    <main>
      <h1>My Categories</h1>
      <table>
        <thead>
          <th>Name</th>
          <th>Number of receipts</th>
        </thead>
        <tbody>
          {% for category in expensecategory_list %}
            <tr>
              <td>{{ category.name }}</td>
              <td>{{ category.receipts.all|length }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>

receipts/templates/receipts/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Receipt</title>
  </head>
  {% include "navbar.html" %}

  <body>
    <main>
      <div>
        <h1>Create Receipt</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button>Create</button>
        </form>
      </div>
    </main>
  </body>
</html>

receipts/templates/receipts/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Receipts</title>
  </head>
  {% include "navbar.html" %}

  <body>
    <main>
      <h1>My Receipts</h1>
      <table>
        <thead>
          <th>Vendor</th>
          <th>Total</th>
          <th>Tax</th>
          <th>Date</th>
          <th>Category</th>
          <th>Account</th>
        </thead>
        <tbody>
          {% for receipt in receipt_list %}
            <tr>
              <td>{{ receipt.vendor }}</td>
              <td>{{ receipt.total }}</td>
              <td>{{ receipt.tax }}</td>
              <td>{{ receipt.date|date:"m-d-Y" }}</td>
              <td>{{ receipt.category }}</td>
              <td>{{ receipt.account }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>